language: objective-c
osx_image: xcode9.4

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Sample.xcworkspace
  - SCHEME=Sample
  - SDK=iphonesimulator11.4
  - RUN_TESTS="YES"
  - POD_LINT="NO"
  matrix:
    - DESTINATION="OS=11.4,name=iPhone X"
    - DESTINATION="OS=10.3.1,name=iPhone 7"
    - DESTINATION="OS=9.3,name=iPhone 6"

install:
  - bundle install

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build App in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

after_success: slather
